<?php


namespace mo3golom\LaravelServiceSkeleton\Methods\Controllers;

use mo3golom\LaravelServiceSkeleton\Methods\Contracts\DirInterface;
use mo3golom\LaravelServiceSkeleton\Methods\File;

class RoutesDirController extends DirController
{
    protected $path = 'Routes';
    protected $subPaths = [];
    protected $file;
    protected $api;

    public function __construct(DirInterface $dir, string $root)
    {
        parent::__construct($dir, $root);
        $this->api = dirname(__FILE__, 3) . '/Templates/api.php';
        $this->file = new File();
    }

    public function check()
    {
        parent::check(); // TODO: Change the autogenerated stub

        $this->file->copy(
            $this->api,
            $this->root . '/' . $this->path . '/api.php'
        );
    }
}